spring:
  application:
    name: PrintDrawingSearchAPI

  datasource:
      url: jdbc:mysql://localhost:3306/printdrawingsdatabase?createDatabaseIfNotExist=true
      username: root
      password: five2one
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update



