spring:
  application:
    name: PrintDrawingSearchAPI
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Or none
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    user: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    locations: classpath:db/migration
    enabled: true