
spring:
  application:
    name: PrintSearchAPI
  datasource:
    url: jdbc:mysql://localhost:3306/printdrawingsdatabase?createDatabaseIfNotExist=true
    username: root
    password: five2one
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
