spring:
  application:
    name: PrintDrawingSearchAPI
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update # Or none
    properties:
      dialect: org.hibernate.dialect.MySQLDialect