spring:
  application:
    name: PrintDrawingSearchAPI
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update # Or none
    properties:
      dialect: org.hibernate.dialect.MySQLDialect


#spring:
#  application:
#    name: PrintDrawingSearchAPI
#  datasource:
#    url: jdbc:mysql://localhost:3306/printdrawingsdatabase?createDatabaseIfNotExist=true
#    username: root
#    password: five2one
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 10
#  jpa:
#    hibernate:
#      ddl-auto: update