spring:
  application:
    name: PrintSearchAPI
  sql:
    init:
      mode: always # or embedded for embedded databases only
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      jdbcUrl: jdbc:mysql://localhost:3306/printdrawingsdatabase
      username: root
      password: five2one
      driver-class-name: com.mysql.cj.jdbc.Driver